* catched Throwable instead of Exception when trying to display   a String representation of the attribute value (since a   NoClassDefFoundError may also be thrown by the code)